DROP DATABASE IF EXISTS tnv_trackerdb;
CREATE DATABASE tnv_trackerdb;
USE tnv_trackerdb;

CREATE TABLE `t_groups_info` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `group_name` VARCHAR(32) DEFAULT NULL,
    `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `t_groups_info` (`group_name`) VALUE ('group001');

CREATE TABLE `t_router` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `appid` VARCHAR(32) DEFAULT NULL,
    `userid` VARCHAR(128) DEFAULT NULL,
    `group_name` VARCHAR(32) DEFAULT NULL,
    `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
